### ISSUE TITLE
Which file and which question should I start from?

### ISSUE THREAD

**Issue by hoseinipeyrov** [ahmadhoseinipeyrov/acm-project#1]
Hello. It's a great job. I saw the files right now. Which file and which question should I start from?

**Comment by ahmadhoseinipeyrov** [comment]
there are 3 problems, 3 codes and a pdf file is solution. you must translate problems and solution and analyse them.

**Comment by ahmadhoseinipeyrov** [comment]
analyse codes

**Comment by ahmadhoseinipeyrov** [comment]
analyze

**Comment by ahmadhoseinipeyrov** [comment]
this comments are private?

**Comment by hoseinipeyrov** [comment]
> there are 3 problems, 3 codes and a pdf file is solution. you must translate problems and solution and analyse them.

Has translation to Persian rating for course?

**Comment by hoseinipeyrov** [comment]
> this comments are private?

no, your repository is public :)

**Comment by ahmadhoseinipeyrov** [comment]
> > there are 3 problems, 3 codes and a pdf file is solution. you must translate problems and solution and analyse them.
> 
> Has translation to Persian rating for course?

yes

**Comment by ahmadhoseinipeyrov** [comment]
> > this comments are private?
> 
> no, your repository is public :)

so bad.

**Comment by hoseinipeyrov** [comment]
> > > there are 3 problems, 3 codes and a pdf file is solution. you must translate problems and solution and analyse them.
> > 
> > 
> > Has translation to Persian rating for course?
> 
> yes

OK, so. the first task should be: translation of questions to Persian language. which question has highest priority؟

**Comment by ahmadhoseinipeyrov** [comment]
Perhaps F
